version: '3.9'

x-logging-rule: &logging-rules
  logging:
    driver: "json-file"
    options:
      max-size: 20m
      max-file: "10"

volumes:
  db-data:

networks:
  server:
    name: server
    external: false
    driver: bridge

services:
  mongodb:
    container_name: mongodb
    image: library/mongo:latest
    env_file:
      - .env
    ports:
      - "27017:27017"
    networks:
      - server
    restart: unless-stopped
    <<: *logging-rules

  server:
    depends_on:
      - mongodb
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - server
    restart: unless-stopped
    <<: *logging-rules
